version: '3.5'

services:
  web:
    build: .
    container_name: open-360-web-server
    hostname: open360-web-server
    restart: on-failure
    environment:
      - PORT=80
    ports:
    - "80:80"
    - "443:443"
    #DEBUG VARIABLES
    #- "9229:9229"
    #command:
    #  - node
    #  - "--inspect-brk=0.0.0.0"
    #  - "main.js"
    #END OF DEBUG
    networks:
      session-network:
      mongodb-network:
      chat-network:
      ingest-network:
      api-network:

networks:
  session-network:
    external: true
    name: "open360-session-network"
  mongodb-network:
    external: true
    name: "open360-mongodb-network"
  chat-network:
    external: true
    name: "open360-chat-network"
  ingest-network:
    external: true
    name: "open360-ingest-network"
  api-network:
    external: true
    name: "open360-api-network"