version: '3.5'

services:
  web:
    build: .
    container_name: open-360-web-server
    restart: on-failure
    links:
      - session-redis
      - mongodb
    environment:
      - PORT=80
    ports:
    - "80:80"
    - "443:443"
    #DEBUG VARIABLES
    #- "9229:9229"
    #command:
    #  - node
    #  - "--inspect-brk=0.0.0.0"
    #  - "main.js"
    networks:
      session-network:
      mongodb-network:
      chat-network:
      ingest-network:

  session-redis:
    image: redis
    container_name: open360-redis-session
    hostname: open360-redis-session
    ports:
    - "6379:6379"
    volumes:
      - "/usr/src/open360/session_data:/data"
      - "/usr/src/open360/redis.conf:/usr/local/etc/redis/redis.conf"
    networks:
      session-network:



  mongodb:
    image: mongo
    container_name: open360-mongodb
    hostname: open360-mongodb
    ports:
      - "27017:27017"
    volumes:
    - "/usr/src/open360/mongo:/data/db"
    networks:
      mongodb-network:

networks:
  session-network:
  mongodb-network:
  chat-network:
    name: "chat-network"
  ingest-network:
    name: "ingest-network"